# Generated by Django 5.0.4 on 2024-04-21 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medico", "0002_dadosmedico"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dadosmedico",
            old_name="especialide",
            new_name="especialidade",
        ),
    ]
