# Generated by Django 5.0.4 on 2024-04-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medico", "0004_datasabertas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasabertas",
            name="data",
            field=models.DateTimeField(),
        ),
    ]
